AllCops:
  Exclude:
    - '*.gemspec'

Style/Documentation:
  Exclude:
    - 'lib/codeunion/version.rb'

Style/FileName:
  Exclude:
    - 'bin/*'

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets

Style/IndentHash:
  EnforcedStyle: consistent


Style/BracesAroundHashParameters:
   EnforcedStyle: braces


Style/WordArray:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/MethodCallParentheses:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25
