AllCops:
  Exclude:
    - '*.gemspec'

Style/Documentation:
  Exclude:
    - 'lib/codeunion/version.rb'

Style/FileName:
  Exclude:
    - 'bin/*'

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets

Style/BracesAroundHashParameters:
   EnforcedStyle: braces


Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/MethodCallParentheses:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25
