AllCops:
  Exclude:
    - '*.gemspec'

Style/Documentation:
  Exclude:
    - 'lib/codeunion/version.rb'

Style/FileName:
  Exclude:
    - 'bin/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
