AllCops:
  Exclude:
    - '*.gemspec'

Style/Documentation:
  Exclude:
    - 'lib/codeunion/version.rb'

Style/FileName:
  Exclude:
    - 'bin/*'

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120
